### ISSUE TITLE
Is it possible  to control to play, stop, playNext, playPre?

### ISSUE THREAD

**Issue by zengkid** [shinyford/nowplaying#1]
is the plugin possible  to control current music player to stop, playnext, playpre, play ?

**Comment by shinyford** [comment]
Hi - so sorry it's taken me so long to reply here.

Sadly, no: the technique in use here only reads the nowplaying state; it can't control it. (Possibly on iOS, but not Android.)

But check out https://pub.dev/packages/audio_service which may be closer to what you need.

**Comment by jja08111** [comment]
You can control using https://stackoverflow.com/a/18909835/14434806 in android
