### ISSUE TITLE
[Feature Request] Add a quick method to Play/Pause/Next/Previous,etc... on Android

### ISSUE THREAD

**Issue by psycoxer** [shinyford/nowplaying#13]
Since `NowPlaying` uses `NotifiationListenerService` , it should be very easy to selectively expose the actions of the media notification as shown [here](https://stackoverflow.com/q/64626372/12491830) 

It would be very convenient as currently the only way to achieve this is through simulating media buttons, which does not work with all players (E.g kde-connect displaying media info of connected devices does not respond to media keys). This would also open up player specific functionality, E.g there is  `Like` action in the spotify notification, which can't be achieved even by simulating keys...

**Comment by shinyford** [comment]
That's interesting @psycoxer - I'll look into it. Nice idea (although a pity it won't translate to iOS too).

**Comment by shinyford** [comment]
Getting back to look at this now, and all things considered I'd rather not add any Android (or iOS) only features. Perhaps a separate package?
