### ISSUE TITLE
Spotify's album cover is out of sync.

### ISSUE THREAD

**Issue by drxddy** [shinyford/nowplaying#15]
I'm not sure if it's a Spotify's issue or nowplaying package's but it's showing album cover of previous track

**Comment by shinyford** [comment]
Okay, that's interesting. Can you let me know what device you're using (I'm guessing Android) and whether it's still happening?

**Comment by drxddy** [comment]
Thanks for the response, I'm testing on Samsung Galaxy M31.

I recorded the behaviour and uploaded it to [youtube as an unlisted video](https://youtu.be/YW2NpgYCmU4), comparing the difference between Spotify and Apple music.

ISSUE2: also I would like to mention another issue which is in the first 10 seconds of the video, where the `Nowplaying.instance.stream` would not send now playing track until you trigger a event manually by pausing or playing or skipping to new track.

If you would like to read my implementation code for this, we can either join a quick call for 5 minutes or I will try to recreate a the same behaviour in a new project, because this one is a closed source project thank you.

ps: in the video for Spotify section (upto 1:45), the album cover is changing to represent the correct one with a small delay and i think this is causing nowplaying package to not observe the changed version of the cover since it got a trigger before the change in album cover from the previous track.

I also tried it in different mid range android from (xaomi, realme, oppo) devices all are behaving similarly, but for apple music and yt music this is not an issue, although even for other streaming services the ISSUE2 mentioned above still persists.

is the ISSUE2 i mentioned above an expected behaviour. the crux of ISSUE2 is that nowplaying is not observing the first Nowplaying track and only observing after an event has occurred like play/pause/skip to next/previous.

Quick links:
 Apple music section starts at [1:45](https://youtu.be/YW2NpgYCmU4?t=105)

Let me know if you want any more information, Thank you.

**Comment by shinyford** [comment]
Thanks for this. Let me watch the video and then see if I can recreate the
behaviour myself first. If not, I'll get back to you and we can pair.

I should say: I may not be able to deal with this terribly quickly, but
I'll do my best.

Cheers

Nic

**Comment by shinyford** [comment]
Hi @dhikshith12 - huge apologies for it having taken me so long to get back to you.

If this is still of interest to you, could you try again with the latest version of NowPlaying? I'm hopeful things will have improved.

**Comment by drxddy** [comment]
Thank you! I'll try the update

**Comment by shinyford** [comment]
Not heard back, so I'll close this now. Please ping me if it still needs attention.
