### ISSUE TITLE
Incompatibility with shared_preferences

### ISSUE THREAD

**Issue by xxjonesriderxx** [shinyford/nowplaying#5]
Log: 

> Because every version of flutter_reusable_code from git depends on shared_preferences ^2.0.5 which depends on shared_preferences_windows ^2.0.0, every version of flutter_reusable_code from git requires shared_preferences_windows ^2.0.0.
And because shared_preferences_windows >=2.0.0 depends on path_provider_platform_interface ^2.0.0, every version of flutter_reusable_code from git requires path_provider_platform_interface ^2.0.0.
And because every version of nowplaying depends on path_provider ^1.6.14 which depends on path_provider_platform_interface ^1.0.1, flutter_reusable_code from git is incompatible with nowplaying.
So, because flutter_hoerluchs depends on both nowplaying ^1.0.2 and flutter_reusable_code from git, version solving failed.

You should update `path_provider ^1.6.14` to `path_provider: ^2.0.1`. Your used version is 16 versions behind the latest.

**Comment by Jellepepe** [comment]
Sadly it seems this project is abandoned.
You could use my fork #2 for now (it is updated for nullsafety & updated depedencies)

**Comment by shinyford** [comment]
Not abandoned, but not checked in on every day. I'll look at the PRs and merge those that look good in the coming days. Thanks for the contributions.

**Comment by Jellepepe** [comment]
> Not abandoned, but not checked in on every day. I'll look at the PRs and merge those that look good in the coming days. Thanks for the contributions.

Thank you for merging, I incorrectly assumed it may have been abandoned since the latest activity was from sept last year. Glad to see I was wrong, this is a very useful plugin 👍

I believe this issue may now be closed as the current version should be compatible with shared_preferences 2.0.3

**Comment by shinyford** [comment]
Thanks. As you can see, I still come back here far too rarely - I shall try to do better.
